### ISSUE TITLE
BAMOE Canvas installtion fails for 9.1 due to extended service pod crashloopbackoff.

### ISSUE THREAD

**Issue by skaraleDMS** [IBM/bamoe#71]
Hi,
We attempted installation of BAMOE 9.1 on EKS (v1.28.12-eks-a18cd3a ). We followed IBM's document. Please find link for the document as follows.

[](https://www.ibm.com/docs/en/ibamoe/9.1.x?topic=installing-canvas)

Issue :
After running

` helm install my-bamoe-canvas ./canvas-helm-chart --values ./canvas-helm-chart/values-kubernetes.yaml --set global.kubernetesClusterDomain="<YOUR_KUBERNETES_CLUSTER_DOMAIN>" --set global.kubernetesIngressClass="<YOUR_KUBERNETES_INGRESS_CLASS>"`
with updated values from terminal extended-service pods keep failing with error log saying expected integer value.

What is Fix ?

To fix above issue we need pass this environment variable to extended service deployment Key: "EXTENDED_SERVICES_PORT" Value: 21345 Then pods become up and running.

OR

Upgrade Kubernetes to v1.30.3+

Please find GIF with action attached with Issue and Fix.
![bamoe-9-rule](https://github.com/user-attachments/assets/65c0a199-f195-41f7-a12b-289b0b448d94)

**Comment by thiagoelg** [comment]
Hi @skaraleDMS, thanks for reporting the issue! 

This is probably related to the pre-populated Environment Variables that Kubernetes generates.
Check these links:
- https://github.com/kubernetes/kubernetes/issues/18219
- https://docs.docker.com/engine/network/links/#environment-variables
- https://github.com/kubernetes/kubernetes/issues/87366
- https://github.com/kubernetes/kubernetes/issues/60099#issuecomment-367820278
- https://github.com/redis/docker-library-redis/issues/53
- https://stackoverflow.com/questions/60736684/kubernetes-exposes-more-environment-variables-than-expected

Our solution would be to explicitly override these environment variables on the Helm Chart or rename the variable so that it is not overwritten.

Upgrading to Kubernetes v1.30.3+ probably works because these environment variables are no longer pre-populated.

**Comment by skaraleDMS** [comment]
Okay, Thanks for the information.
